CREATE TABLE assigned_shifts
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   BIGINT,
    preset_id BIGINT,
    CONSTRAINT pk_assigned_shifts PRIMARY KEY (id)
);

CREATE TABLE shift_weight_presets
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_shift_weight_presets PRIMARY KEY (id)
);

CREATE TABLE shift_weights
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    day       VARCHAR(255),
    shiftType VARCHAR(255),
    weight    INTEGER                                 NOT NULL,
    preset_id BIGINT,
    CONSTRAINT pk_shift_weights PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    password VARCHAR(255),
    score    INTEGER,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE assigned_shifts
    ADD CONSTRAINT FK_ASSIGNED_SHIFTS_ON_PRESET FOREIGN KEY (preset_id) REFERENCES shift_weight_presets (id);

ALTER TABLE assigned_shifts
    ADD CONSTRAINT FK_ASSIGNED_SHIFTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE shift_weights
    ADD CONSTRAINT FK_SHIFT_WEIGHTS_ON_PRESET FOREIGN KEY (preset_id) REFERENCES shift_weight_presets (id);