-- Add role column to users table
ALTER TABLE users
    ADD COLUMN role VARCHAR(255) DEFAULT 'user';

-- Create constraints table
CREATE TABLE constraints
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    shift_date      DATE                                    NOT NULL,
    shift_type      VARCHAR(255)                            NOT NULL,
    constraint_type VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_constraints PRIMARY KEY (id),
    CONSTRAINT fk_constraints_user FOREIGN KEY (user_id) REFERENCES users (id)
);

-- Add missing columns to assigned_shifts if they don't exist (for Shift base class fields)
ALTER TABLE assigned_shifts
    ADD COLUMN date DATE;
ALTER TABLE assigned_shifts
    ADD COLUMN type VARCHAR(255);


