-- Initial migration based on review of all JPA entities in the project

-- Create users table
CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    password VARCHAR(255),
    role     VARCHAR(255) DEFAULT 'user',
    score    INTEGER,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- Create shift_weight_presets table
CREATE TABLE shift_weight_presets
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_shift_weight_presets PRIMARY KEY (id)
);

-- Create assigned_shifts table
CREATE TABLE assigned_shifts
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT,
    preset_id BIGINT,
    date    DATE,
    type    VARCHAR(255) CHECK (type IN ('DAY', 'NIGHT')),
    CONSTRAINT pk_assigned_shifts PRIMARY KEY (id)
);

-- Create constraints table
CREATE TABLE constraints
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         BIGINT                                  NOT NULL,
    shift_date      DATE                                    NOT NULL,
    shift_type      VARCHAR(255)                            NOT NULL CHECK (shift_type IN ('DAY', 'NIGHT')),
    constraint_type VARCHAR(255)                            NOT NULL CHECK (constraint_type IN ('CANT', 'PREFER', 'PREFERS_NOT')),
    CONSTRAINT pk_constraints PRIMARY KEY (id)
);

-- Create shift_weights table
CREATE TABLE shift_weights
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    day VARCHAR(255) CHECK (day IN ('SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY')
) ,
    shiftType VARCHAR(255) CHECK (shiftType IN ('DAY', 'NIGHT')),
    weight INTEGER NOT NULL,
    preset_id BIGINT,
    CONSTRAINT pk_shift_weights PRIMARY KEY (id)
);

-- Add foreign key constraints
ALTER TABLE assigned_shifts
    ADD CONSTRAINT FK_ASSIGNED_SHIFTS_ON_PRESET FOREIGN KEY (preset_id) REFERENCES shift_weight_presets (id);

ALTER TABLE assigned_shifts
    ADD CONSTRAINT FK_ASSIGNED_SHIFTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE constraints
    ADD CONSTRAINT fk_constraints_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE shift_weights
    ADD CONSTRAINT FK_SHIFT_WEIGHTS_ON_PRESET FOREIGN KEY (preset_id) REFERENCES shift_weight_presets (id);
