-- Recreate tables with correct schema based on Hibernate entities

-- Drop existing tables if they exist (in reverse order of dependencies)
DROP TABLE IF EXISTS shift_weights CASCADE;
DROP TABLE IF EXISTS constraints CASCADE;
DROP TABLE IF EXISTS assigned_shifts CASCADE;
DROP TABLE IF EXISTS shift_weight_presets CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Create users table
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    password VARCHAR(255),
    role VARCHAR(255),
    score INTEGER,
    PRIMARY KEY (id)
);

-- Create shift_weight_presets table
CREATE TABLE shift_weight_presets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    PRIMARY KEY (id)
);

-- Create assigned_shifts table
CREATE TABLE assigned_shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT,
    preset_id BIGINT,
    PRIMARY KEY (id)
);

-- Create constraints table
CREATE TABLE constraints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    constraint_type VARCHAR(255) NOT NULL CHECK (constraint_type IN ('CANT', 'PREFER')),
    shift_date DATE NOT NULL,
    shift_type VARCHAR(255) NOT NULL CHECK (shift_type IN ('DAY', 'NIGHT')),
    user_id BIGINT NOT NULL,
    PRIMARY KEY (id)
);

-- Create shift_weights table
CREATE TABLE shift_weights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    day VARCHAR(255) CHECK (day IN ('SUNDAY', 'MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY')),
    shiftType VARCHAR(255) CHECK (shiftType IN ('DAY', 'NIGHT')),
    weight INTEGER NOT NULL,
    preset_id BIGINT,
    PRIMARY KEY (id)
);

-- Add foreign key constraints
ALTER TABLE assigned_shifts ADD CONSTRAINT FK4gjulnh3o7e34k85pwh46cfyx FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE assigned_shifts ADD CONSTRAINT FKrtx3wlwdcskwsbpoygfodkcga FOREIGN KEY (preset_id) REFERENCES shift_weight_presets (id);
ALTER TABLE constraints ADD CONSTRAINT FKf7r56kas3yx1hx2y713ud0gyq FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE shift_weights ADD CONSTRAINT FKf36e26prro4rn954n8hpyn5r2 FOREIGN KEY (preset_id) REFERENCES shift_weight_presets (id);

