-- Refresh tokens: opaque random tokens, stored hashed (SHA-256 hex) so a DB leak doesn't leak usable tokens
CREATE TABLE refresh_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    token_hash VARCHAR(64)                             NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
    CONSTRAINT uq_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);
